[NETWORK]
ContractAddress = 0x26EB6312B10cBC43ef6bCFbe76FBA571463b5Ddb
NetworkIP = 127.0.0.1
BCBaseAddress = http://127.0.0.1
AbiLocation = ./data/ecs/smart_contract_abi.json
WebSocket = ws://127.0.0.1:10002/ws

[NODES]
Certifiers = 3
Sequencers = 3
Verifiers = 3
PollInterval = 1
WorkerInterval = 2
LazyWorkers = 1
# Specifies how many tasks a lazy worker maliciously fakes
LazyWork = 3
LazyWorkerPercentages = [10, 20, 30, 40]

[LOGGING]
LogName = ecs
LogFile = occp_naive.log
LogDir = ./data/logs

[MALICIOUS]
; 1 = Non-Malicious; 2 = SequenceHashAttack; 3 = ERA
User = 1
Worker = False

[DATA]
ResultBaseDir = ./data/resultsNaive
LocalResultDir = local
OccpResultDir = occp

[EXPERIMENT]
NumberReruns = 30
; If set to True only the current settings from this config file will be considered (malicious user, ...)
RunSingleTest = False
Steps = [100000]
StepsOccp = [100000]
DumpDir = ./data/experiments
ProgramBaseDir = ./data/programs
Programs = ["fibonacci", "fibonacci_iterative_pretty", "lanczos", "spf", "merge_sort", "matrix_mul"]
ProgramsOccp = ["fibonacci", "fibonacci_iterative_pretty", "lanczos", "spf", "merge_sort", "matrix_mul"]
UserRerun = False

[STORAGE]
BucketName = ecs
AWSAccessKey = test
AWSSecretKey = test
RegionName = us-east-1



Endpoint = http://localhost:4566

Respond to this review in the same context as before using the following points.
Review: The paper addresses a recently hot topic in computer science: How program executions (tests, scientific computations) can be validated to decide whether they were run in the way and produced the results that were presented. The proposed solution has two main components: A programming platform (MONA language and Mona Interpreter) that allows stopping, saving, reloading and continuing program executions while producing traces; And a blockchain-based algorithm that allows the distributed validation of the executions. The authors provided a Proof of Concept implementation and performed some measurements.

Although the proposed method sounds, I have doubts about its technical feasibility. First, saving the whole (relevant) memory state of the execution would result in a huge amount of data for every halt/resume points of the program. Second, the MONA language selected for the PoC implementation seems to be a "toy" language. Feasibility on real programming languages is still a question (although I think it is feasible for many languages, I'm not sure it is worth). These problems are mentioned in the threats to validity section.

On P3::left::L27-32 in the sentence "Each program expression ..." the authors state that seqid naturally aligns with execution order, which is only true for very simple, sequential programs.

Points:
-  As also suggested by another reviewer we added a subsection stating the assumptions under which our language works.
- The seqId represents the respected semantic ordering of expression evaluation that the interpreter should evaluate to execute the program.
- Multi-threading or concurrent program this expected sequence still stands as the expected evaluation order. 
- Our current implementation is limited to deterministic and single-threaded programs. We adjusted the paper to explicitly state that our approach cannot yet handle randomness or multi-threading.
We have introduced a new subsection (2.1 Assumptions) that explicitly outlines the assumptions on which our approach is based. This section clarifies key assumptions such as the need for deterministic and sequential (single-threaded) programs.
We have further emphasised the difference between assumptions that apply specifically to the current implementation and those that hold for the general approach. We address these points in the section “Conclusion and future work”.
-





Respond to this review in the same context as before using the following points.
Review: The paper addresses a recently hot topic in computer science: How program executions (tests, scientific computations) can be validated to decide whether they were run in the way and produced the results that were presented. The proposed solution has two main components: A programming platform (MONA language and Mona Interpreter) that allows stopping, saving, reloading and continuing program executions while producing traces; And a blockchain-based algorithm that allows the distributed validation of the executions. The authors provided a Proof of Concept implementation and performed some measurements.

Although the proposed method sounds, I have doubts about its technical feasibility. First, saving the whole (relevant) memory state of the execution would result in a huge amount of data for every halt/resume points of the program. Second, the MONA language selected for the PoC implementation seems to be a "toy" language. Feasibility on real programming languages is still a question (although I think it is feasible for many languages, I'm not sure it is worth). These problems are mentioned in the threats to validity section.

On P3::left::L27-32 in the sentence "Each program expression ..." the authors state that seqid naturally aligns with execution order, which is only true for very simple, sequential programs.

Points:
-  As also suggested by another reviewer we added a subsection stating the assumptions under which our language works.
- The seqId represents the respected semantic ordering of expression evaluation that the interpreter should evaluate to execute the program.
- Multi-threading or concurrent program this expected sequence still stands as the expected evaluation order. 
- Future research can add support for concurrent evaluations by adding an annotation layer that represent the thread evaluating that block, the block which is naturally annotated through the seqId strategy.
- Assuming optimisations on the protocol the validation may still succeed if the likelyhood of reaching the snapshot where the output is altered by a concurrent side-effect is statistically likely to happen in the number of retries expected by the protocol. Thus one of the workers should achieve the same sequence of expected execution.

This is true as in that particular snapshot all the thread information including the progress in the evaluation in the sequence (i.e represented by the seqID strategy). Thus, a worker is able to continue the evaluation of all those threads under the same exact conditions in which the original "user" executed this same instance. Of course this would lead to workers apear to be malicious workers increasing the cost of such evaluations. To this front future work may consider the implementation of a likelyhood evaluation strategy. Which given some threshold would establish wheter that sequence is probable.


Correct spelling and grammar mistakes also rephrase it to be awesome.
The seqId represents the expected semantic ordering of expression evaluation that the interpreter evaluates to execute the program.
In Multi-threading or concurrent programs this expected sequence still stands as the expected order of evaluation. 
Future research can add support for concurrent evaluations by adding an annotation layer that represent the thread evaluating that block, the block which is naturally annotated through the seqId strategy.
Assuming optimisations on the protocol the validation may still succeed if the likelyhood of reaching the snapshot where the output is altered by a concurrent side-effect is statistically likely to happen in the number of retries expected by the protocol. Thus one of the workers should achieve the same sequence of expected execution.

This is true as in that particular snapshot all the thread information including the progress in the evaluation in the sequence (i.e represented by the seqID strategy). Thus, a worker is able to continue the evaluation of all those threads under the same exact conditions in which the original "user" executed this same instance. Of course this would lead to workers apear to be malicious workers increasing the cost of such evaluations. To this front future work may consider the implementation of a likelyhood evaluation strategy. Which given some threshold would establish wheter that sequence is probable.











The seqId represents the expected semantic ordering of expression evaluations that the interpreter follows to execute the program. In multi-threaded or concurrent programs, this sequence continues to represent the anticipated order of evaluation. Future research could extend support for concurrent evaluations by incorporating a sequentially numbered annotation layer that identifies the thread evaluating a specific block—naturally annotated through the seqId strategy—which indicates the evaluation progress of that thread within its assigned code derivation. This would allow a memory snapshot to evolve, capturing information about all currently running threads at that specific point in time.

Assuming the certification protocol introduced in this work is used, validation can still succeed if the likelihood of reaching a snapshot where the output is altered by a concurrent side effect remains statistically probable within the expected number of retries. In such cases, one of the workers is expected to achieve the intended sequence of execution, provided that the execution is valid and not maliciously manipulated.

This remains true because, in that specific snapshot, all thread-related information—including evaluation progress, as represented by the seqId strategy—is preserved. Consequently, a worker can continue evaluating all threads under the exact same conditions as the original execution. However, this might lead to workers being perceived as malicious, thereby increasing the overall cost of evaluation. To mitigate this, future work may explore implementing a likelihood evaluation strategy that uses a threshold to determine whether a given sequence is plausible.

Overall, the slicing of a sequential program through the snapshotting strategy can be adapted to the snapshotting of non-sequential programs, where the evaluation step reached by each thread is represented by it the seqId of that thread. As a result, the reproducibility of concurrent scenarios is limited to that particular snapshot and does not affect the complexity of verifying prior or subsequent snapshots.


