version: "3.8"

services:
  localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
      image: localstack/localstack
      ports:
        - "127.0.0.1:4566:4566"            # LocalStack Gateway
        - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      environment:
        - SERVICES=s3
        - DEBUG=1
        - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
        - DOCKER_HOST=unix:///var/run/docker.sock
        - SKIP_SSL_CERT_DOWNLOAD=1
        - SKIP_INFRA_DOWNLOADS=1
        - DISABLE_EVENTS=1
      volumes:
        - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
#  localstack:
#    build:
#      context: ./localstack
#      dockerfile: Dockerfile
#    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      - SERVICES=s3
#      - DEBUG=1
#      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - SKIP_SSL_CERT_DOWNLOAD=1
#      - SKIP_INFRA_DOWNLOADS=1
#      - DISABLE_EVENTS=1
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#
#  polygon:
#    build:
#      context: ./polygonNetwork  # Set the context to the subfolder "polygonNetwork"
#      dockerfile: Dockerfile
#    container_name: polygon
#    volumes:
#      - ./polygonNetwork/test-chain-1:/poly/test-chain-1  # Update volume paths
#      - ./polygonNetwork/test-chain-2:/poly/test-chain-2  # Update volume paths
#      - ./polygonNetwork/test-chain-3:/poly/test-chain-3  # Update volume paths
#      - ./polygonNetwork/test-chain-4:/poly/test-chain-4  # Update volume paths
#    working_dir: /poly
#    command: ["./startNodes.sh"]
#    depends_on:
#      - localstack
